Bubobubobubobubo/sardine

examples/XX_playground.py
sardine/__init__.py
sardine/clock/Clock.py

Making very small progress on error handling and made code more readable.

code is bit clearer

---

sardine/__init__.py
sardine/clock/AsyncRunner.py
sardine/clock/Clock.py
sardine/io/UserConfig.py
sardine/todo.md

This PR aims to reintroduce two features:
1. Asynchronous functions, allowing users to run non-blocking I/O like network access:
```py
@swim
async def bpm(delay=1):
c.bpm = await fetch_bpm()
cs(bpm)
```
2. A sleep function for writing in a more imperative style similar to other algorithmic languages like SonicPi:
```py
@swim
def func(delay=4):
sleep(3)
for _ in range(3):
S('909').out()
sleep(1/2)
cs(func)
```
Previously the clock system only supported a declarative paradigm for delayed sounds like this example:
```py
@swim
def func(delay=4):
for i in (6, 7, 8):
S('909', at=i/2).out()
cs(func)
```
With a `time.sleep(n)` or `await asyncio.sleep(n)` approach, if a function sleeps longer than their next scheduled time, the runner will be unable to call the function on time and will have to …

Add support for async functions + sleep() function

---

README.md
cli/main.py
setup.py

Adding new configuration tools, see commits for more information. The `README.md` file has been updated to document their usage.

Configuration CLI

---

docs/sardinopedia.md
sardine/__init__.py
sardine/clock/Clock.py
sardine/sequences/Iterators.py
sardine/sequences/LexerParser/ListParser.py
sardine/sequences/LexerParser/TreeCalc.py
sardine/sequences/LexerParser/grammars/proto.lark

```python
@swim 
def bd(d=0.5):
if random() > 0.5:
i.I = 0
S('ee:i.I', speed='1', shape=0.5).out()
again(bd, d=0.5)
```
To be documented soon with the docs overhaul.

Adding a new weird way to write iterators

---

docs/sardinopedia.md
sardine/__init__.py
sardine/clock/Clock.py
sardine/sequences/LexerParser/ListParser.py
sardine/sequences/LexerParser/TreeCalc.py
sardine/sequences/LexerParser/grammars/proto.lark
sardine/sequences/Variables.py

- The prototype works pretty well.
- Their behavior is documented in the Sardinopedia.

Adding amphibian variables and iterators.

---

docs/sardinopedia.md
fishery/__main__.py
sardine/__init__.py
sardine/clock/Clock.py
sardine/io/MIDISender.py
sardine/io/OSCSender.py
sardine/io/SuperDirtSender.py
sardine/sequences/LexerParser/TreeCalc.py
sardine/sequences/Sequence.py

There is now a better syntax for running recursive functions really fast. This will bring better rhythmical precision while conserving the ability to pattern things like if the function was slow. This new mode can work in conjunction with the slow sardine mode. It has been documented in the `Sardinopedia` in a new addendum to the first section.
A few examples concerning sampling have also been added to the Sardinopedia :)

Introducing VFS mode: Very Fast Sardine

---

docs/sardinopedia.md

Added missing "=" in speed= value in 3 code samples Sample playback speed
Sample playback volume (2)

Update sardinopedia.ma to fix speed syntax

---

docs/sardinopedia.md

Changed code samples to remove  ".out(i)" from print(P()) calls and add the iterator back wi the pattern.  Numbers
Time Tokens

Fixed code samples

---

docs/reference.md

Made a few tweaks to typical range values.

Edits to SD effects settings

---

sardine/io/MIDISender.py
sardine/io/SenderLogic.py
sardine/io/SuperDirtSender.py
sardine/sequences/LexerParser/Chords.py
sardine/sequences/LexerParser/FuncLibrary.py
sardine/sequences/LexerParser/TreeCalc.py
sardine/sequences/LexerParser/grammars/proto.lark

**Sardine** is now polyphonic: 
- Both **M()** and **S()** can play chords.
- Chords are denoted by `<` and `>` wrapping a list.
- Chord inversion is denoted by using `^`: `C@maj7^2`. 
This is not a big change if we speak about number of lines or things that had to be refactored but this will lead to the emergence of a new category of problems! I will have to bugfix / make it better so that people can play very expressive melodic gestures using polyphonic notation.

Adding Polyphony to Sardine

---

sardine/io/SenderLogic.py
sardine/io/SuperDirtSender.py
sardine/sequences/LexerParser/Chords.py
sardine/sequences/LexerParser/FuncLibrary.py
sardine/sequences/LexerParser/ListParser.py
sardine/sequences/LexerParser/TreeCalc.py
sardine/sequences/LexerParser/grammars/proto.lark

A chord is now a subclass of a list.

Deeper polyphony

---

docs/documentation/demos/dumpster_dive.md

made code substitutions to reflect the sardine-sounds repo added the audio effects and preset dictionaries
updated description

Update dumpster_dive.md on website_overhaul branch

---

docs/documentation/sardinopedia/basic_swimming_lessons.md

Pa >> None added the the How to stop surfing section

Update basic_swimming_lessons: add >> None

---

pyproject.toml

This PR adds several more trove classifiers that apply to sardine.

Add more relevant trove classifiers

---

sardine/handlers/player.py

This updates the Player class to use the same iterator count across each pattern that its given to play. The iterator count will reset itself back to 0 whenever the internal runner has stopped. The iterator parameter for the play() method now defaults to None and can be used to override the current iterator once the pattern runs.

Use persistent iterator for Player

---

sardine/scheduler/async_runner.py

This fixes a regression where AsyncRunners using the deferred state mechanism (e.g. swimming functions decorated with `@swim` or `@swim(snap=<some number>)`) wouldn't retain the arguments from the previous state when the runner was updated. This used to be the expected behaviour for states in the v0.1.0 implementation, and the original is still there to a degree, but was only implemented for non-deferred states via [`AsyncRunner.push()`][1].
```py
>>> @swim
... def foo(p=1, i=1):
...     print(i)
...     again(foo, i=i + 1)
...
╭───────────────────╮
│ [foo is swimming] │
╰───────────────────╯
>>> 1
2
3
4
5
@swim
... def foo(p=1, i=1):
...     print(i)
...     again(foo, i=i + 1)
...
>>> 6
7
╭────────────────╮
│ [Updating foo] │
╰────────────────╯
8  # Prior to this change, `i` would have …
```

Fix arguments not being transferred to deferred states

---

sardine/handlers/superdirt.py
sardine/run.py
sardine/sequences/sardine_parser/funclib.py
sardine/sequences/sardine_parser/sardine.lark
sardine/sequences/sardine_parser/tree_calc.py

There is no need to rush in that direction for the moment. Merging with main to focus on more pressing matters.

Merging experimental local branch into 'main'

---

fishery/client/package-lock.json
fishery/client/src/lib/components/Console.svelte
fishery/client/src/lib/components/Editor.svelte
fishery/client/src/lib/services/runnerService.ts
fishery/client/src/routes/+layout.svelte
fishery/client/src/routes/+layout.ts
fishery/client/yarn.lock

Shift + Enter is back \o/
Logs are flooowing 
( but I may have to reconsider it 🤔)

Rewires the front and the back :)

---

fishery/client/src/lib/services/runnerService.ts
fishery/client/src/routes/+layout.svelte

Fix error on dispatch, should fix "(JS) Changing the internal buffer will toggle a weird behavior when inserting new lines or deleting characters. Each of these operations is essentially repeated, making two new lines appear or deleting two characters."

148-sardine-gui

---

.gitignore
sardine/logger/logger.py
sardine/superdirt/process.py

New try at merging some fixes for Windows. Using endoding at open() and forcing double backslashes to supercollider load.

Fixing Windows issues

---

.gitignore
fishery/client/src/lib/components/Console.svelte
fishery/client/src/lib/components/buttons/IconBtn.svelte
fishery/client/src/routes/+layout.svelte
fishery/client/src/routes/Header.svelte
fishery/server/flask_server.py

A decent chunk of this is just my IDE reformatting +layout.svelte, but there are a couple of bug fixes too -- specifically stringifying the buffers prior to saving them, plus the tutorial text works now.

Fishery web bugfixes

---

docs/sardine_doc/src/SUMMARY.md
docs/sardine_doc/src/diving_deeper/python.md

Still working on this but wanted to get input.

Add python.md to diving_deeper

---

docs/sardine_doc/src/audio_engine/filtering.md

fix mistake in bandq value range
add  bandpass example

more filtering.md edits

---

docs/sardine_doc/src/diving_deeper/sleeping.md

- adds example for Patterning sleep
- minor wording edits

edits to sleeping.md

---

docs/sardine_doc/src/SUMMARY.md
docs/sardine_doc/src/diving_deeper/extensions.md
sardine_core/io/UserConfig.py
sardine_core/run.py

This PR introduces a new extension/plugin system to allow creating custom handlers and using them in Sardine sessions.
This system is documented and an example of a such extension is provided.

Plugin system for custom handlers

---

README.md
docs/sardine_doc/src/editors/vim.md

- **Fix iron.nvim configuration**
- **Add mdbook install doc**

Fix iron-nvim configuration doc
