sardine/__init__.py, sardine/clock/AsyncRunner.py, sardine/clock/Clock.py
The `AsyncRunner` class is now dedicated to handling of one runner task per scheduled function. When the `Clock.schedule()` method is called consecutively, it notifies the existing AsyncRunner task to continue in the next iteration, rather than starting up a new runner task to handle a single iteration.
In addition, separate messages are shown when the function state is reloaded or has to be restored. `Clock.schedule()` will now introspect the default value for the `delay=` parameter in submitted functions if the function is (re)scheduled without a delay argument.
A fix is also included for `Clock.run_clock()` incrementing the clock phase too quickly.
ImportError is now caught when importing `uvloop`, since the package cannot be installed on Windows.
Demonstration:
```py
>>> async def …
```
=> Rewrite scheduler and fix clock timing

sardine/clock/AsyncRunner.py
This limits the maximum number of function states that are tracked on each runner to reduce memory consumption over time.
Most often only 2 states are needed, since errors usually occur on the newest function only. However, it is possible for errors to propagate to older functions, such as using a wrong type on a global variable that was used across multiple function states. The current limit is arbitrarily set to 3, but may be increased if necessary.
https://github.com/Bubobubobubobubo/Sardine/blob/c72ccbef401986afcc443a40940ca7600713e932/sardine/clock/AsyncRunner.py#L13
=> Limit the number of function states per runner

sardine/__init__.py, sardine/clock/AsyncRunner.py, sardine/clock/Clock.py, sardine/clock/__init__.py, sardine/io/MidiIo.py, sardine/io/MidiListener.py, sardine/io/Osc.py, sardine/io/UserConfig.py, sardine/io/__init__.py, sardine/sequences/__init__.py, sardine/superdirt/AutoBoot.py, sardine/superdirt/SuperDirt.py, sardine/superdirt/__init__.py
To simplify cross-package import statements, this PR allows functions, classes, and objects to be imported from Sardine subpackages, specifically `clock`, `io`, `sequences`, and `superdirt`.
This also adds `__all__` variables to hide any imported functions in modules when using `from .mod import *`.
=> Allow importing objects from packages directly

sardine/clock/AsyncRunner.py, sardine/clock/Clock.py
This improves the responsiveness by allowing scheduled functions to immediately reload and/or recalculate their next beat when the user updates the function or changes the `bpm`, `ppqn`, or `accel`.
This also adds the ability to manually shift the clock's current tick for synchronization purposes:
```py
from sardine import *
c.tick -= 4           # Moves 4 ticks backwards
c.tick += c.ppqn * 3  # Moves 3 beats forwards
```
When the tick is updated this way, all functions are re-scheduled but sounds will play at their expected time (i.e. if a sound specifies `at=8`, it will still play 8 beats in the future, regardless of what the tick is set to in that time span).
=> Improve clock responsiveness and synchronization

sardine/io/MIDISender.py, sardine/io/OSCSender.py, sardine/io/Osc.py, sardine/io/SuperDirtSender.py
- added `cps` for delay and temporal effects calculation.
- fixed a bug with i (iter) in some objects
=> Clock attributes are now sent in the basic OSC SuperDirt message

sardine/sequences/Sequence.py
Main fix: 
*  Previously euclidean_rhythm(8,5) returned `[1, 0, 1, 0, 1, 0, 1, 1]` 
*  Now it returns correctly `[1, 0, 1, 1, 0, 1, 1, 0]`
Features :
* More doc
* Added the lo and hi parameters, as they might be useful for some users. Maybe they should be allowed to be floats?
Basically inspired by Foxdot as referenced in the inline doc
=> fix: the euclidian rhythm function should work

docs/sardinopedia.md
The existing sample files used in the Sample Position and Sample Stretching are not native to SuperDirt ('long'). I changed S sender to use 'fire' from the SD samples. It is a longer file that works well with different begin/end values and yields noticeable distortion with different timescale values. 
I also added a sentence in the SC Object that SC is only available when booting SC from Sardine.
=> Change samples in Sardinopedia Sample section

sardine/sequences/LexerParser/grammars/proto.lark, tests/test_pattern_parsing.py
see https://github.com/Bubobubobubobubo/sardine/issues/87
In this PR we introduce a new syntax for ramps in the pattern language: `[start:end]` and `[start:end,step]` instead of `{start,end}` and `{start,end,step}`.
This main advantage of this new syntax is to avoid using `{` and `}` in the grammar so we can apply Python formatting to patterns.
=> [grammar] new ramp syntax

docs/documentation/sardinopedia/pattern_language.md
The second "!" was missing in the code example.
=> Correct !! in example

pyproject.toml
This updates sardine to source prebuilt wheels for the LinkPython dependency using my [LinkPython-extern][1] fork.
I've also uploaded prebuilt wheels for python-rtmidi on a [separate repository][2], which can be used with pip to include them when installing sardine with the following command:
```sh
pip install --find-links https://thegamecracks.github.io/python-rtmidi-wheels/ .
```
Unfortunately the choice to not create another package for python-rtmidi means that the regular `pip install .` command will not have access to the rtmidi prebuilt wheels.
This PR is pending an update to the documentation to describe the new installation instructions.
[1]: https://pypi.org/project/LinkPython-extern/
[2]: https://github.com/thegamecracks/python-rtmidi-wheels
=> Use prebuilt wheels for LinkPython and python-rtmidi

pyproject.toml
Hatch was not properly configured to recognize which package directories were meant to be included with the installation, preventing non-editable (regular) installs from working correctly.
This is fixed by adding `fishery` and `sardine` to pyproject.toml as targets for wheels.
=> Fix regular install not copying fishery and sardine

pyproject.toml
LinkPython-extern 1.0.1 has newly released with support for 3.11. With this package updated, it will hopefully resolve the last pains with installing sardine for 3.11.
=> Update dependencies to support Python 3.11

pyproject.toml
Updates the license metadata in accordance with [hatch docs][1] so `pip show sardine` doesn't dump the entirety of GPL-3.0 in its summary.
[1]: https://hatch.pypa.io/latest/config/metadata/#__tabbed_10_2
=> Correct license descriptions in package metadata

sardine/base/clock.py, sardine/scheduler/async_runner.py, sardine/utils/__init__.py
- AsyncRunner now uses an updated `_get_corrected_interval()` algorithm that no longer relies on delta to be recorded.
Drift correction is only handled within _call_func() if deferred scheduling is enabled.
- `get_beat_time()` and `get_bar_time()` can now accept a time= parameter which overrides the default `shifted_time`. This is used by `_get_corrected_interval()` and `get_snap_deadline()` to avoid microsecond drifting resulting from different time measurements being used.
The result of the above changes is that `_expected_time` is much more precise/consistent, making AsyncRunner less likely to drift over time.
=> Improve drift correction for AsyncRunner once again

sardine/base/clock.py
This is mostly to mitigate the rapid iteration bug that might occur as a result of rounding errors. This issue was not noticed on Windows, but unix systems seem to have a habit of doing double iterations likely due to their more precise clocks.
=> Increase error tolerance in get_beat_time()

docs/documentation/reference.md, docs/documentation/sardinopedia/basic_swimming_lessons.md, docs/documentation/sardinopedia/melody.md, docs/documentation/sardinopedia/pattern_language.md, docs/documentation/sardinopedia/patterning.md, docs/documentation/sardinopedia/rhythm.md, docs/documentation/sardinopedia/sampling.md, docs/documentation/sardinopedia/senders.md, docs/technical/installation.md, sardine/sequences/sardine_parser/sardine.lark
This PR aims at updating the user documentation after v0.2 rewrite since it introduced several syntax changes.
Syntax changes to document:
=> [docs] syntax update after v0.2 rewrite

docs/technical/installation.md
Due to this faulty merge commit 75d8e59, a small part of the original content in the installation docs was not correctly merged with changes from the documentation branch. This PR is to restore that content to a state that makes sense.
This PR also fixes #150.
=> Cleanup the mess in first section of installation docs

sardine/handlers/osc_loop.py
Certain callbacks depend on the event loop, e.g. call_timed() invoked by senders, making this change a necessity for those to work.
This change may impact the performance of the event loop. However, idle CPU usage was low to begin with so this likely will not lead to a significant difference.
=> Rewrite OSCLoop to run in the event loop's thread

docs/sardine_doc/src/SUMMARY.md, docs/sardine_doc/src/showcase.md, docs/sardine_doc/src/showcase/transport_variations.md
Add transport_variations.md 
Modify SUMMARY.md to add page
Add text to showcase.md to encourage submissions.
=> Showcase updates

sardine_core/fish_bowl.py, sardine_core/handlers/midi.py
Although the docs state that the `duration` parameter is in beats, in practice it was in seconds. This commit adds a `sleep_beats` method to the FishBowl, which is called instead of sleep in the `send_off` method of `MidiHandler`.
=> Fix MIDI note duration handling

sardine_core/clock/internal_clock.py, sardine_core/clock/link_clock.py, sardine_core/scheduler/async_runner.py, sardine_core/scheduler/scheduler.py
Implementing a new hook to fix unsync bug when the tempo is changing.
=> Attempt to fix unsync bug

sardine_core/handlers/player.py, sardine_core/scheduler/async_runner.py
This PR fixes runners occasionally running more than once in a single iteration, causing players to go out of phase.
=> Fix occasional double iterations when reloading runners
